### ISSUE TITLE
Remapping Caps Lock to Ctrl when holding and Escape when tapping.

### ISSUE THREAD

**Issue by zkanda** [blahlicus/animus-family#10]
Hi guys.

I'm looking for a keyboard and as such I'm trying to find the right firmware for a keyboard.

I have a question for keyboard mapping. I'm a vim user so it's probably a bit specific but in particular, here's what I'm hoping to achieve.

When holding caps lock key, it would become control.
When tapping caps lock key, it would become escape.

I'm currently using a software to do it but it would be good to be able to make it in the hardware.
You can find more information here: http://www.economyofeffort.com/2014/08/11/beyond-ctrl-remap-make-that-caps-lock-key-useful/

So is this possible for animus firmware?

**Comment by blahlicus** [comment]
Hey, yes, it is possible to do what you want with Animus, this is called the dual roles key in Animus, map the `Esc || L Ctrl` key to your device via the key menu in [Arbites](https://unikeyboard.io/arbites/), you could do so by following [this guide](https://github.com/blahlicus/arbites-family/wiki/How-to-Rebind-Keys).

**Comment by zkanda** [comment]
This is awesome, thank you.
