### ISSUE TITLE
Dual-roles win/gui/cmd key

### ISSUE THREAD

**Issue by blahlicus** [blahlicus/animus-family#11]
see [this](https://github.com/blahlicus/arbites-family/issues/5).

Function request to add the win/gui/cmd key to the dual roles module.

**Comment by raquo** [comment]
MacOS doesn't use Ctrl at all for shortcuts, so MacOS users are sorely missing all the Animus/Arbites Ctrl-based functionality.

Apart from dual-roles, also missing are `Win'd`, `Win Shift'd`, `Win Alt'd`, and `Win Shift Alt'd` tabs. The first three constitute the vast majority of shortcuts in MacOS and MacOS apps. Should I create a separate issue for those? Seems like these two issues might be related.

**Comment by blahlicus** [comment]
Completed as of [x3.0.0 release](https://github.com/blahlicus/animus-family/releases/tag/x3.0.0).

**Comment by raquo** [comment]
Awesome, thanks for doing this and the other tickets!
