### ISSUE TITLE
Releasing a dual key after holding it down for a while sends unexpected key

### ISSUE THREAD

**Issue by raquo** [blahlicus/animus-family#19]
Common scenario I run into all the time: I have a dual key defined like `commaShift`. Sometimes I press it intending to use it as Shift, but then release it after half a second or so without pressing any other key. Sometimes that's because I changed my mind, or realized that I need Alt instead of Shift. Happens all the time.

Currently in this scenario the dual key will fire a comma (if it's commaShift) when you release it. This is annoying because it's unexpected, and for some key combinations that I use like endShift it takes a lot of keypresses to recover.

I propose that the comma key (in case of commaShift) should only be sent if the delay between pressing and releasing that key was lower than some threshold, e.g. maybe 200ms. If more time has elapsed, send a lone shift keypress instead (which will probably have no effect but seems more correct than the other alternative, sending nothing).

**Comment by raquo** [comment]
Another common problem with this behaviour is <modifier>-clicking.

Suppose you press a dual shift key, then click a mouse to e.g. select a range of text or items in some GUI application. When you then release the dual shift key, its non-modifier key will fire (so if it was `endShift`, then the `End` key will fire, scrolling down whatever window you were looking at.

**Comment by blahlicus** [comment]
Good suggestions, I'll add these in for 3.0 enhancements in anticipation for the next generation products, I'll get it done over Christmas once I'm free from my masters finals.

**Comment by raquo** [comment]
Awesome, thanks, looking forward to it. Good luck with the finals! :)

**Comment by GuilloOme** [comment]
Also, the problem have been reported here: https://www.reddit.com/r/Blahlicus/comments/7by5en/animus_25_2role_issues/

**Comment by blahlicus** [comment]
Completed as of [x3.0.0 release](https://github.com/blahlicus/animus-family/releases/tag/x3.0.0).

**Comment by GuilloOme** [comment]
@blahlicus, since the release of 3.0.0 as `stable` is delayed. Would it be possible to have a partial release like 2.8 for this fix only?

thanks,
