### ISSUE TITLE
Shift dual keys do not work with each other

### ISSUE THREAD

**Issue by raquo** [blahlicus/animus-family#20]
I have the following dual keys defined: `commaShift`, `endShift`

If I press a dedicated `R Shift` ("right Shift") key and `commaShift`, I will get **`<`** (Shift-ed comma, the desired outcome).

However, if in the example above I press a dedicated `L shift` ("left Shift") key instead of `R Shift`, I will get an unshifted comma, which is surprising and makes it impossible (without other special keys) to get a **`<`** character if you don't have a dedicated `R Shift` key in your layout, very much limiting the usefulness of such a dual key.

Moreover, if in the example above I press `endShift` instead of `L Shift`, in addition to getting a **`,`** instead of the desired **`<`**, the `End` key will also fire when I release `endShift`, screwing up cursor position. I guess that might be related to #19. Needless to say, that behaviour is also very inconvenient.

**Comment by blahlicus** [comment]
Completed as of [x3.0.0 release](https://github.com/blahlicus/animus-family/releases/tag/x3.0.0).
