### ISSUE TITLE
Toggled layers and their behavior with macros

### ISSUE THREAD

**Issue by slampisko** [blahlicus/animus-family#25]
I have a dedicated layer just for [Plover](http://www.openstenoproject.org/) (Layer 4) which I activate with the _toggleFn4_ special key. I wanted to define a macro in this layer that would press some keys for me, but stay in the steno layer, however, I found out by experimentation that this is not possible.

When I simply created a macro and assigned it to a key on Layer 4, the keyboard would reset to Layer 0 when the macro completed. I tried to add another "key", _toggleFn4_, at the end of the macro, but that had no effect.

I already learned to live with the fact that regular Fn keys always reset the keyboard to Layer 0 when released, so I need to either not have any of them on the layer or make a mental note in my head about which layer I'm currently on and update that whenever I press layer keys. But I was expecting macros to work.

It would be great if this could be fixed.

**Comment by blahlicus** [comment]
Animus 2's macro module calls `ReleaseAllKeys()` which returns the user to the main layer which is causing the problem you are experiencing. [Animus 3's macro module](https://github.com/blahlicus/animus-family/blob/master/animus-3/source/animus/ModMacro.h) corrects this behaviour and does not return you to the main layer, it should be out in a bit, but the accompanying arbites version is not ready yet.

In the mean time, if you are willing to compile your own version, then you could edit the file `animus_main.ino` in your build by deleting [this line](https://github.com/blahlicus/animus-family/blob/master/animus/animus_main.ino#L300) and the macros will no longer return you to layer 0 after a macro

**Comment by slampisko** [comment]
That worked! After deleting that line, macros no longer reset to layer 0 when run from a toggled layer. Thanks for your help.
