### ISSUE TITLE
dual keys stop working - animus 3

### ISSUE THREAD

**Issue by BlackCapCoder** [blahlicus/animus-family#27]
It is possible for dual keys (space || shift, enter || ctrl) to lose their second functionality. For instance, `backspace || shift` might suddenly start acting as a regular backspace. Once one dual key stop working, all the other dual keys also stop working.

I am unable to reproduce the behavior at will, but it eventually happens, usually during heavy typing. A restart fixes the issue. I am using a brand new diverge 4.

**Comment by blahlicus** [comment]
Do you have steps for me to replicate the bug? Are you pressing multiple dual roles keys whilst switching the layer(via FN keys) at the same time? Even doing so should not cause this bug. I checked the source and it seems to me the only way for this bug to occur is if the `ShiftDown` counter is not working properly:

```
      if (ShiftDown == 0) // shift was not down by this mod before
      {
        Animus.PressKey(ANIMUS_MOD_DUALROLES_LSHIFT, 0);
        PressedKey = false;
        ShiftTimeout = TimeoutLength;
      }
      else // shift was already down, pretend to be an ordinary key
      {
        Animus.PressKey(val, 0);
      }
      ShiftDown++;
```

In the above code snippet for the `press key` event handle, `ShiftDown` is incremented every time a dual role shift key is pressed, in the `release key` event handle, there's a similar code snippet where it is decremented every time a dual role shift key is released, the only way for the bug to happen is if a `release key` event was never followed by a `press key` event.

**Comment by BlackCapCoder** [comment]
Have one button be `space || shift` and one be `backspace || shift`, each on one half of a diverge 4. Open up a text editor and hold down any letter until you have about 100. Start spam pressing `backspace || shift` to delete the letters, and press `space || shift` in small bursts every few seconds. I am able to consistently reproduce the issue before I run out of letters.

**Comment by BlackCapCoder** [comment]
https://github.com/blahlicus/animus-family/blob/81f074a83722be4aeb501e9906576d4714493cb1/animus-3/source/animus/ModDualRoles.cpp#L222

Changing this line to `if (ShiftDown > 0) ShiftDown--;` fixes the issue for me. I guess it is possible for `ReleaseKey` to be called twice?

**Comment by blahlicus** [comment]
Wow, thanks for letting me know, do you want to submit a PR so that you get the contribution or would you prefer that I do it?

Sorry I wasn't able to follow up on this sooner, I've been pretty tied up lately on refactoring Arbites and real life issues.

**Comment by BlackCapCoder** [comment]
According to my testing, the main (but not the only) culprit to `ReleaseKey` being called more often than `PressKey` is the second call to `ReleaseKey` here:
https://github.com/blahlicus/animus-family/blob/81f074a83722be4aeb501e9906576d4714493cb1/animus-3/source/animus/ModDualRoles.cpp#L222-L233

Is there any reason not to move this inside the second if?

**Comment by blahlicus** [comment]
The intent was to make sure `PressKey` from double key presses always get to release because releasing the key when it wasn't press doesn't matter in the HID level (`ReleaseKey` removes the specified scancode byte from the HID payload, it doesn't do anything if the specific scancode isn't already in the HID payload)
```
      if (GuiDown == 0) // gui was not down by this mod before
      {
        Animus.PressKey(ANIMUS_MOD_DUALROLES_LGUI, 0);
        PressedKey = false;
        GuiTimeout = TimeoutLength;
      }
      else // gui was already down, pretend to be an ordinary key
      {
        Animus.PressKey(val, 0); <----------------- this line
      }
      GuiDown++;
```

So for example, if I pressed `space || shift`, then press `1 || shift`, then I'd be able to get `!`, this system was made in response to #20.

Removing that line would prevent the second dualrole key from releasing. I could have added another counter in but I didn't want to waste memory and it didn't matter if ReleaseKey was being spammed in the scope of HID functionality.
