### ISSUE TITLE
Diverge 3 debouncing issues still occuring with Animus 2.7.0

### ISSUE THREAD

**Issue by manofsteele08** [blahlicus/animus-family#30]
Just updated to Animus 2.7.0 on my Diverge 3. I saw one of the major updates to this version is that the debouncing issues have gone away. This has not been my experience. On 2.3.1 I had to adjust the builder_refresh to be around 14 to be somewhat stable. On 2.6.0 i found that about 17 for the builder_refresh rate was the most tolerable. On 2.7.0 however, even at 100, the debouncing issues are still strong. The higher I raise it sure, they start to go away but, of course this makes the keyboard much less efficient. I would really like to be running 2.7.0 but, the debouncing issue is really frustrating. Thoughts? Something else I can try? Thanks!

**Comment by BlackCapCoder** [comment]
@manofsteele08 Do you experience the issue more frequently on the side of the keyboard that is not plugged in to the computer?

I am having similar issues on a diverge 4 running animus 3. I am not familiar with the animus 2 codebase, but I understand that the cooldown system was back ported. I seem to have the issue more frequently on the right half, the issues on the left half could be attributed to human error as I am new to the keyboard.

**Comment by BlackCapCoder** [comment]
I propose adding another variable called `DebounceInc` and changing the following code:
https://github.com/blahlicus/animus-family/blob/81f074a83722be4aeb501e9906576d4714493cb1/animus-2/animus/animus_main.ino#L68-L75

To:
```c
if (KeyStateCoolDown[j][i] == 0) // if key was not recently released
{
  ModPressCoord(j, i);
  LayerState[j][i] = TempLayer;
  ModPrePress(GetValEEPROM(j, i, TempLayer), GetTypeEEPROM(j, i, TempLayer));
  PressKey(GetValEEPROM(j, i, TempLayer), GetTypeEEPROM(j, i, TempLayer));
  KeyStateCoolDown[j][i] = 255;
} else if (KeyStateCoolDown[j][i] != 255) {
  KeyStateCoolDown[j][i] += DebounceInc;
  if (KeyStateCoolDown[j][i] > RefreshDelay)
  {
    KeyStateCoolDown[j][i] = RefreshDelay;
  }
}
```

-----

With the old code I need a `RefreshDelay` of about 100 to mitigate debounce, but with the new one I can do with both `RefreshDelay` and `DebounceInc` set to 10, which gives me a much more responsive keyboard!

To showcase this I have the LED's under my keys light up while `KeyStateCoolDown > 0`, IE: while a LED is on I cannot repress that key.

Old code, 100 `RefreshDelay`: https://youtu.be/8upbhVoZmD8
New code, 10/10: https://youtu.be/xeO95-br6_Y

**Comment by manofsteele08** [comment]
@BlackCapCoder I have not really noticed a difference between the two halves as far as one debouncing more than the other goes. However, and this may be edge case, it seems that some keys specifically are more sensitive to the debouncing than others. There could be a number of reasons for that. I re-checked all my solders just to make sure nothing was loose or not having full contact but everything is good. Ok, confession time. I probably could have been a better community member by diving in the code and trying to contribute (shame face), as you have with your most recent post. But I haven't yet and, as a TEST, I flashed QMK on my board. Right out of the gate, the debouncing was gone 100%. There is a Diverge 3 port in the repo and I was able to modify it for my layout. It feels sooo good! But I wanted to prove that I had not messed up on my own assembly. Now that I have, and know that it's a firmware thing, I would love to get this resolved and figure out a way to go back to Animus debounce free!! It's really late right now so I will work on parsing your code change more tomorrow. How much more responsive is the keyboard with the change? I watched your videos and visually I can see an improvement on the LEDs but, is the debounce gone completely? Or just very minimal?

**Comment by BlackCapCoder** [comment]
I typed on the keyboard for a couple of hours yesterday without noticing any debounce, so either way it's a huge improvement. I jumped from 40 to 55 wpm from making less errors.

**Comment by blahlicus** [comment]
@BlackCapCoder Great job finding a fix for this persisting issue. Your contributions can't be overstated.

I read through the code and ran it on my Diverge 4 and everything seems fine, I had a difficult time understanding the logic behind it but now I get it.

Basically, the hardware bouncing is causing the key to be released early in the firmware whilst the key is still being held down physically. Hence, the countdown reaches 0 whilst the key is still held down, then this line (`if (Global.KeyStateCoolDown[j][i] == 0)`) goes through and a double press would occur.

Your solution resets the countdown value to `refreshDelay` if `KeyState` is high whilst countdown is not completed, a very brilliant fix indeed.

This also explained why I didn't catch this error when I was debugging the problem because I had set the refresh delay value to 255 when testing it and never held, released, then held the key for more than 255ms.

Do you want to submit another PR for this? A quick note on code convention again, I prefer lonely curly brackets so please put some newlines into your elseif statement to separate the brackets.

**Comment by blahlicus** [comment]
A problem I do foresee with this solution is it's effect on rapidly pressing keys.

Suppose I set the resetDelay to 200 and intent to tap my key once every 100ms, I will not be able to get my expected output. I tested this with refreshDelay set to 50 (which is a value that people might use) and it does affect my ability to rapidly tap keys.

Instead of the current fix, how about we add in a minimum time before the key could be released? Bouncing occurs the moment when you physically press the key so if we have a minimum time of 5ms before a key could be released, we could have large refreshDelay values without affecting the ability to rapidly tap keys.

**Comment by blahlicus** [comment]
Here's my proposed fix (Code not tested it's 6:30AM here and I'm going to bed, will test tomorrow):

```
    // start of physical key loops
    for (byte i = 0; i < Global.ROW; i++) // this is placed inside the 1ms delay to slow it down a bit
    {
      for (byte j = 0; j < Global.COL; j++)
      {
        if (Global.KeyState[j][i] == HIGH) // if key is down
        {
          if (Global.KeyStateCoolDown[j][i] == 0) // if key was not recently released
          {
            PressCoords(j, i);
            Global.LayerState[j][i] = Global.TempLayer;
            PrePress(PersMem.GetKeyData(j, i, Global.TempLayer), PersMem.GetKeyType(j, i, Global.TempLayer));
            PressKey(PersMem.GetKeyData(j, i, Global.TempLayer), PersMem.GetKeyType(j, i, Global.TempLayer));
            Global.KeyStateCoolDown[j][i] = 255;
          }
        }
        else if (Global.KeyState[j][i] == LOW) // if key is up
        {
          if (Global.KeyStateCoolDown[j][i] == 255 - DebounceWindow) // if key was previously held down
          {
            ReleaseKey(PersMem.GetKeyData(j, i, Global.LayerState[j][i]), PersMem.GetKeyType(j, i, Global.LayerState[j][i]));

            Global.KeyStateCoolDown[j][i] = Global.RefreshDelay;
          }
        }
      }
    }
    // end of physical key loops
    // start of countdowns
    for (byte i = 0; i < Global.ROW; i++)
    {
      for (byte j = 0; j < Global.COL; j++)
      {
        if (Global.KeyStateCoolDown[j][i] > 0 && Global.KeyStateCoolDown[j][i] != 255 - DebounceWindow)
        {
          Global.KeyStateCoolDown[j][i]--;
        }
      }
    }
```

The above code with `DebounceWindow` set to 5 would prevent a key from releasing if it was physically released within 5ms of being pressed, which would be the window for physical bouncing to happen.

**Comment by BlackCapCoder** [comment]
I tested your code and it does indeed solve the issue.

I might be missing something terribly obvious here, but what is even the point of setting `KeyStateCoolDown` to `Global.RefreshDelay` if not to debounce? Your solution effectively solves bouncing by not releasing the key within the 5ms debounce frame, so why prevent the user from pressing the key again?

How about:
```c
for (byte i = 0; i < Global.ROW; i++) // this is placed inside the 1ms delay to slow it down a bit
{
  for (byte j = 0; j < Global.COL; j++)
  {
    if (Global.KeyState[j][i] == HIGH) // if key is down
    {
      if (Global.KeyStateCoolDown[j][i] == 0) // if key was not recently released
      {
        PressCoords(j, i);
        Global.LayerState[j][i] = Global.TempLayer;
        PrePress(PersMem.GetKeyData(j, i, Global.TempLayer), PersMem.GetKeyType(j, i, Global.TempLayer));
        PressKey(PersMem.GetKeyData(j, i, Global.TempLayer), PersMem.GetKeyType(j, i, Global.TempLayer));
        Global.KeyStateCoolDown[j][i] = Global.RefreshDelay;
      }
    }
    else if (Global.KeyState[j][i] == LOW) // if key is up
    {
      if (Global.KeyStateCoolDown[j][i] == 1) // if key was previously held down
      {
        ReleaseKey(PersMem.GetKeyData(j, i, Global.LayerState[j][i]), PersMem.GetKeyType(j, i, Global.LayerState[j][i]));
        Global.KeyStateCoolDown[j][i] = 0;
      }
    }
  }
}
// end of physical key loops
// start of countdowns
for (byte i = 0; i < Global.ROW; i++)
{
  for (byte j = 0; j < Global.COL; j++)
  {
    if (Global.KeyStateCoolDown[j][i] > 1)
    {
      Global.KeyStateCoolDown[j][i]--;
    }
  }
}
```

**Comment by blahlicus** [comment]
Yeah you are right, there is no longer a need for the previous debouncing mechanism, this would suffice. The above code looks clean, do you want to PR this as is?

I suppose this was what I wanted to do from the beginning which is to prevent a key from being pressed again within `refreshDelay`ms without affecting the entire matrix.

**Comment by manofsteele08** [comment]
This is awesome. Great work! I'd like to try testing this on 2.7.0 (since i believe you are running Animus 3?) before you do a PR, just to be sure. That ok? I left my keyboard at work so I won't get to it till tomorrow and I can test it tomorrow night MST. Unless one of you can test it before then haha

**Comment by blahlicus** [comment]
@manofsteele08 Sure, below is the above code snippet but for Animus 2.7, you'll have to manually edit that into your copy of the source code. (Let me know if you prefer that I send you a complete `animus_main.ino` file instead)

Please make sure your `builder_refresh` is larger than 0, a value like 5 or 10 should work very well already and you shouldn't need a larger value.

```
  if (CheckMillis())
  {
    KeyScan(); // physical key layers scanned
    // start of physical key loops
    for (byte i = 0; i < ROW; i++) // this is placed inside the 1ms delay to slow it down a bit
    {
      for (byte j = 0; j < COL; j++)
      {
        if (KeyState[j][i] == HIGH) // if key is down
        {
          if (KeyStateCoolDown[j][i] == 0) // if key was not recently released
          {
            ModPressCoord(j, i);
            LayerState[j][i] = TempLayer;
            ModPrePress(GetValEEPROM(j, i, TempLayer), GetTypeEEPROM(j, i, TempLayer));
            PressKey(GetValEEPROM(j, i, TempLayer), GetTypeEEPROM(j, i, TempLayer));
            KeyStateCoolDown[j][i] = RefreshDelay;
          }
        }
        else if (KeyState[j][i] == LOW) // if key is up
        {
          if (KeyStateCoolDown[j][i] == 1) // if key was previously held down
          {
            ReleaseKey(GetValEEPROM(j, i, LayerState[j][i]), GetTypeEEPROM(j, i, LayerState[j][i]));

            KeyStateCoolDown[j][i] = 0;
          }
        }
      }
    }
    // end of physical key loops
    // start of countdowns
    for (byte i = 0; i < ROW; i++)
    {
      for (byte j = 0; j < COL; j++)
      {
        if (KeyStateCoolDown[j][i] > 1)
        {
          KeyStateCoolDown[j][i]--;
        }
      }
    }
    //end of countdowns
  }
```

Animus 3 can actually run on the atmega32u4 based platforms (Diverge 3, 2, 1, etc) but I haven't gotten around to getting the EEPROM configs for those sorted out yet, you should be able to run Animus 3 once I'm done dealing with the various messes that are happening with Animus 3 and Diverge 4.

**Comment by manofsteele08** [comment]
I can try and build it but if it's easy for you to build a new .ino and send it, that works just as well too.

**Comment by BlackCapCoder** [comment]
I am very rarely getting double presses with the latest code. To fix this I made two separate delays `Global.RefreshDelayDown` and `Global.RefreshDelayUp`, where the former is for the press event, and the latter is for release. Another solution would be to wait for `Global.RefreshDelay * 2` milliseconds and fire the release event when `KeyStateCoolDown == Global.RefreshDelay`, if we want to avoid another variable.

**Comment by BlackCapCoder** [comment]
One thing to consider in the case of having two separate delays is that `Global.RefreshDelay` is also used for the `AsyncRefreshDelay` function, which is currently unused.

**Comment by manofsteele08** [comment]
Ok update. So I re-flashed with the modified code based on your suggestions and it is drastically better. Definitely a step in the right direction. Couple of things though:

1. I set the RefreshDelay to 5 per the suggestion and it was good. But higher numbers still yielded better results of debouncing. However, higher numbers aren't always good.

2. I am now seeing what @BlackCapCoder was describing previousely about one half having more issues than the other. My right half, the debouncing is minimal. The left half however it's still noticeable. So maybe there is something there?

Anyways, it's a definite improvement but unfortunately I am still seeing it enough that it affects performance :(

Let me know how else I can help.

**Comment by BlackCapCoder** [comment]
@manofsteele08 Sit tight, I posted a PR that fixes the issue! You have debounce issues on the left half because of #34, which I have another PR ready for once the first one has been processed.

**Comment by BlackCapCoder** [comment]
@blahlicus This still needs to be backported to animus 2. I would, but I don't have hardware to test it on.

**Comment by manofsteele08** [comment]
@BlackCapCoder I see your PR's. Awesome!!! Thank you!

**Comment by blahlicus** [comment]
I'm currently reviewing the PR, it is quite complex so it'll take maybe around 2 days for me to read through and test it properly on both SAMD21 hardware and Atmega32u4 hardware.

Backporting it will not be an issue, I'll be submitting a PR for the backport once I'm done reading through the SAMD21 implementation.

**Comment by raquo** [comment]
I was losing my mind with key chatter after upgrading to Animus 2.7 (from 2.3.x), but the 2.8 release fixes the problem completely for me (Diverge 3). Thanks for your work guys!
