### ISSUE TITLE
Add tap dance module

### ISSUE THREAD

**Issue by blahlicus** [blahlicus/animus-family#8]
Enhancement as per [this feature](https://www.reddit.com/r/MechanicalKeyboards/comments/5974z2/ortholinear_and_columnarstaggered_users/d97tsam/?context=3)

**Comment by algernon** [comment]
I developed the original tap-dance feature for QMK, if I can be of any assistance, let me know.

**Comment by blahlicus** [comment]
completed as per 2.3, closing obsolete issue.
